=== FaleMMR/AE2XML/bin/validador.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
	<!ELEMENT biblioteca (libros, revistas, periodicos)> 
	<!ELEMENT libros (libro+)>
	<!ELEMENT libro (titulo, capitulos, indice, sinopsis)> 
			       <!ELEMENT titulo (#PCDATA)>
			       <!ELEMENT indice (#PCDATA)>
			       <!ELEMENT sinopsis (#PCDATA)>
	<!ELEMENT capitulos (capitulo+)> 
	<!ELEMENT capitulo (titulo, contenido)> 
	
	
	
	<!ELEMENT revistas (revista+)> 
	<!ELEMENT revista (titulo, numerorevista, indice, secciones)> 
			      
			       <!ELEMENT numerovista (#PCDATA)>
			     
	<!ELEMENT secciones (seccion+)> 
	<!ELEMENT seccion (contenido)> 
			 <!ELEMENT contenido (#PCDATA)>
	
	
	
	<!ELEMENT periodicos (periodico+)> 
	<!ELEMENT periodico (secciones , indice)>
	<!ELEMENT secciones (seccion+)> 
	<!ELEMENT seccion (articulos+)> 
	<!ELEMENT articulos (articulo+)> 
	<!ELEMENT articulo (contenido)> 
	
		   
	<!ATTLIST libro numpaginas CDATA #REQUIRED > 
	<!ATTLIST libro tipo_clase (novela|infantil|didactico) #REQUIRED > 
	<!ATTLIST libro id ID #REQUIRED> 			
    <!ATTLIST capitulo numpaginas CDATA #REQUIRED> 
    
	<!ATTLIST revista numpaginas CDATA #REQUIRED> 
    <!ATTLIST revista tipo_clase (informatica|corazon|coches|investigacion) #REQUIRED> 
    <!ATTLIST revista id ID #REQUIRED> 
    <!ATTLIST seccion numpaginas CDATA #REQUIRED> 
	<!ATTLIST contenido enlace CDATA #REQUIRED> 
	
	
    <!ATTLIST periodicos fechapublicacion CDATA #REQUIRED > 	
    <!ATTLIST periodicos tipo_clase (nacionales|internacionales) #REQUIRED > 	
    <!ATTLIST periodicos id ID #REQUIRED> 	
    <!ATTLIST seccion tipo_seccion  (economica|opinion|deportes|nacional|internacional)  #REQUIRED> 	
    <!ATTLIST articulo autor CDATA #REQUIRED> 	
    <!ATTLIST contenido enlace CDATA #REQUIRED > 	
]>

=== FaleMMR/AE2XML/src/practicaAE2conDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "validador.dtd">


<biblioteca>

	<libros>

		<libro numpaginas="11" tipo_clase="novela" id="L8765">
			<titulo>XXXX</titulo>


			<capitulos>
			
				<capitulo numpaginas="11">
					<titulo>asdfas</titulo>
					<contenido>asdfasdf</contenido>
				</capitulo>
				
				<capitulo numpaginas="11">
					<titulo>asdfas</titulo>
					<contenido>asdfasdf</contenido>
				</capitulo>
				
			</capitulos>

			<indice>XXXX</indice>
			<sinopsis>XXXX</sinopsis>

		</libro>

	</libros>


	<revistas>
		<revista  numpaginas="11" tipo_clase="coches" id="R76q34">
			<titulo>asdasdf</titulo>
			<numerorevista>asdfasdf</numerorevista>
			<indice>asdfasdf</indice>
			<secciones>
				<seccion  numpaginas="11">
					<contenido enlace="asfdasdfasfda"></contenido>
				</seccion>
			
			
			</secciones>
		
		</revista>

	</revistas>

	<periodicos>
		<periodico fechapublicacion="11/12/2022" tipo_clase="nacionales" id="P7656" >
			<secciones>
				<seccion  tipo_seccion="deportes">
					<articulos>
						<articulo autor='PEPE'>
							<contenido enlace="asfdasdfasfda"></contenido>
						</articulo>
					
					</articulos>
		
				</seccion>
			</secciones>
			<indice>dfbdfbb</indice>
			
		
		
		</periodico>

	</periodicos>


</biblioteca>
